// src/app/atom/cms-html-renderer/cms-html-renderer.tsx
import React from 'react';
import { CmsDataType, CmsHeadlineType } from '../../types/cms.types';
import DOMPurify from 'dompurify';

interface CmsHtmlRendererProps {
    data: CmsDataType[];
    headline?: CmsHeadlineType[];
    colorTitle?: string;
}

const CmsHtmlRenderer: React.FC<CmsHtmlRendererProps> = ({ data, headline, colorTitle = 'dark' }) => {

    // List of generated ids
    const listGenerateId: string[] = [];

    /**
     * Function to generate an id
     * @param text 
     * @param withoutPush 
     * @returns 
     */
    const generateId = (text: string, withoutPush = false): string => {
        const sanitizedText = text.toLowerCase().replace(/[^a-z0-9]/g, '');
        if (!listGenerateId.includes(sanitizedText) && !withoutPush) {
            listGenerateId.push(sanitizedText);
        }
        return sanitizedText;
    };

    /**
     * Function to scroll to an id
     * @param id 
     */
    const scrollToId = (id: string): void => {
        const element = document.getElementById(id);
        if (element) {
            const yOffset = -100;
            const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
            window.scrollTo({ top: y, behavior: 'smooth' });
        }
    };

    /**
     * Function to check if the text is a table
     * @param text 
     * @returns 
     */
    const isTable = (text: string | undefined): boolean => {
        return text !== undefined && [
            "[tableau-1]",
            "[tableau-2]",
            "[tableau-3]",
            "[tableau-4]",
            "[tableau-5]",
            "[tableau-6]",
            "[tableau-7]",
            "[tableau-8]",
            "[tableau-9]",
            "[tableau-10]",
        ].includes(text.trim());
    };

    /**
     * Function to check if the text is a headline
     * @param text 
     * @returns 
     */
    const isHeadline = (text: string | undefined): boolean => {
        return text !== undefined && [
            "[headline-1]",
            "[headline-2]",
            "[headline-3]",
            "[headline-4]",
            "[headline-5]",
            "[headline-6]",
            "[headline-7]",
            "[headline-8]",
            "[headline-9]",
            "[headline-10]",
        ].includes(text.trim());
    };

    /**
     * Function to get the headline
     * @param text 
     * @returns 
     */
    const getHeadline = (text: string | undefined): CmsHeadlineType => {
        const headlineIndex = text?.replace('[', '').replace(']', '').split('-');
        if (headlineIndex && headline) {
            return headline[Number(headlineIndex[1]) - 1];
        }
        return {};
    };

    /**
     * Function to render the content
     * @param d 
     * @param index 
     * @returns 
     */
    const renderContent = (d: CmsDataType, index: number) => {
        switch (d.type) {
            case 'heading4':
                return <h4 key={index} className={`text-lg font-semibold text-${colorTitle} mb-2`}>{d.text}</h4>;
            case 'heading3':
                return <h3 key={index} className={`text-xl font-semibold text-${colorTitle} mb-3`}>{d.text}</h3>;
            case 'heading2':
                return <h2 key={index} id={d.id} className={`text-2xl font-semibold text-${colorTitle} mb-4`}>{d.text}</h2>;
            case 'paragraph':
                // Check if the paragraph is a special headline
                if (isHeadline(d.text)) {
                    const headlineData = getHeadline(d.text);
                    // Render a special headline block
                    return (
                        <div key={index} className="my-4 bg-blue-50 border border-blue-500 rounded-lg p-6">
                            <h4 className="flex items-center text-blue-500 mb-3 text-lg font-semibold">
                                <img src="/assets/images/icons/chat.svg" alt="chat" className="mr-3" />
                                {headlineData.headline_title}
                            </h4>
                            {headlineData.headline_body?.map((b, i) => (
                                <p key={i} dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(b.text || '') }} className="text-sm" />
                            ))}
                        </div>
                    );
                }
                // Render a regular paragraph
                return <p key={index} className="mb-4 text-sm" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(d.text || '') }} />;
            case 'image':
                return <img key={index} src={d.url} alt={d.alt} className="w-auto h-auto rounded-lg my-4" />;
            case 'list-item':
            case 'o-list-item':
                // Skip rendering if it's not the first item of its type
                if (index > 0 && data[index - 1].type === d.type) {
                    return null;
                }
                // Determine if it's an ordered or unordered list
                const ListComponent = d.type === 'o-list-item' ? 'ol' : 'ul';
                const listClass = d.type === 'o-list-item' ? 'list-decimal' : 'list-disc';
                const listItems = [];
                let i = index;
                // Group consecutive list items of the same type
                while (i < data.length && data[i].type === d.type) {
                    listItems.push(data[i]);
                    i++;
                }
                // Render the list
                return (
                    <ListComponent key={index} className={`${listClass} list-inside mb-4`}>
                        {listItems.map((item, i) => (
                            <li key={i} className="mb-1 text-sm">
                                {listGenerateId.includes(generateId(item.text || '', true)) ? (
                                    // If the item is a link to another section, render it as an anchor
                                    <a href={`#${generateId(item.text || '', true)}`} onClick={() => scrollToId(generateId(item.text || '', true))} className="text-blue-500 hover:underline">
                                        {item.text}
                                    </a>
                                ) : (
                                    // Otherwise, render it as plain text
                                    item.text
                                )}
                            </li>
                        ))}
                    </ListComponent>
                );
            default:
                return null;
        }
    };

    return (
        <div className="cms-html-renderer-container w-full">
            {data.map((d, index) => renderContent(d, index))}
        </div>
    );
};

export default CmsHtmlRenderer;

// src/app/atom/cms-html-renderer-angular/cms-html-renderer.component.ts
import { Component, OnInit, Input, SecurityContext } from '@angular/core';
import {CmsArrayType, CmsDataType, CmsHeadlineType} from "../../types/cms.types";
import { CmsService } from "../../services/cms.service";
import {environment} from "../../../environments/environment";
import { DomSanitizer } from '@angular/platform-browser';

@Component({
  selector: 'CmsHtmlRendererAtom',
  templateUrl: './cms-html-renderer.component.html',
  styleUrls: ['./cms-html-renderer.component.scss'],
})
export class CmsHtmlRendererComponent implements OnInit {

  /** Color for Title */
  @Input() colorTitle: string = "";

  /** Data of rich text */
  @Input() data: Array<CmsDataType> = [];

  /** Data of headline */
  @Input() headline: Array<CmsHeadlineType> = [];

  /** Array 1 */
  @Input() array1: Array<CmsArrayType> = [];

  /** Array 2 */
  @Input() array2: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array3: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array4: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array5: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array6: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array7: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array8: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array9: Array<CmsArrayType> = [];

  /** Array 3 */
  @Input() array10: Array<CmsArrayType> = [];

  

  /** List of generate id */
  listGenerateId: string[] = [];

  constructor(
    public cms: CmsService,
    private sanitizer: DomSanitizer
  ) {}

  ngOnInit(): void {
    for (let item of this.data) {
      if (item.text)  item.text = item.text.replace('https://www.monabee.fr/portfolio-item', `${environment.url}/blog`)
      if (item.text)  item.text = item.text.replace('https://d3u5slsagqox11.cloudfront.net', `${environment.url}`)

      if (item.spans) {
        for (const span of item.spans) {
          if (span.type === "hyperlink" && span.data.url) span.data.url = span.data.url.replace('https://www.monabee.fr/portfolio-item', `${environment.url}/blog`);
          if (span.type === "hyperlink" && span.data.url) span.data.url = span.data.url.replace('https://d3u5slsagqox11.cloudfront.net', `${environment.url}`);
        }
      }

      if(item.text && item.type == "heading2"){
        item.id = this.generateId(item.text);
      }
    }
  }

  /**
   * Get the list item
   * @param index
   * @param currentTag
   */
  public getListItem(index: number, currentTag: CmsDataType): Array<CmsDataType> {
    let items: Array<CmsDataType> = [];
    let tag = currentTag.type;

    while (this.data.length >= index && (tag === "list-item" || tag === "o-list-item")) {
      items.push(this.data[index]);
      index++;
      tag = this.data[index] !== undefined ? this.data[index].type : "";
    }

    return items;
  }

  /**
   * Is array
   */
  public isTable(text: string|undefined): boolean {
    return text !== undefined && [
      "[tableau-1]",
      "[tableau-2]",
      "[tableau-3]",
      "[tableau-4]",
      "[tableau-5]",
      "[tableau-6]",
      "[tableau-7]",
      "[tableau-8]",
      "[tableau-9]",
      "[tableau-10]",
    ].indexOf(text.trim()) !== -1;
  }

  /**
   * Is headline
   */
  public isHeadline(text: string|undefined): boolean {
    return text !== undefined && [
      "[headline-1]",
      "[headline-2]",
      "[headline-3]",
      "[headline-4]",
      "[headline-5]",
      "[headline-6]",
      "[headline-7]",
      "[headline-8]",
      "[headline-9]",
      "[headline-10]",
    ].indexOf(text.trim()) !== -1;
  }

  /**
   * get the headline
   */
  public getHeadline(text: string|undefined): CmsHeadlineType {
    const headlineIndex = text?.replace('[', '').replace(']', '').split('-');

    if (headlineIndex) {
      return this.headline[Number(headlineIndex[1])-1];
    } else return {};
  }

  /**
   * Get the array
   */
  public getTable(text: string): string {
    let array: Array<CmsArrayType> = [];
    if (text.trim() === "[tableau-1]") array = this.array1;
    if (text.trim() === "[tableau-2]") array = this.array2;
    if (text.trim() === "[tableau-3]") array = this.array3;
    if (text.trim() === "[tableau-4]") array = this.array4;
    if (text.trim() === "[tableau-5]") array = this.array5;
    if (text.trim() === "[tableau-6]") array = this.array6;
    if (text.trim() === "[tableau-7]") array = this.array7;
    if (text.trim() === "[tableau-8]") array = this.array8;
    if (text.trim() === "[tableau-9]") array = this.array9;
    if (text.trim() === "[tableau-10]") array = this.array10;

    // Return empty string if the array is unknown
    if (array.length === 0) return "";

    let html = "";
    // Loop over the row
    for (const index in array) {
      const row = array[index];

      // Split the row with the comma and loop over
      const items = row.row.split(';');
      html += "<tr>";

      for (const item of items) {
        if (Number(index) == 0) html += `<th>${item}</th>`;
        else html += `<td>${item}</td>`;
      }

      html += "</tr>";
    }

   return `<table>${html}</table>`;
  }


  /**
   * Generate the id
   */
  generateId(text: string, withoutPush = false): string {
    const sanitizedText = this.sanitizer.sanitize(SecurityContext.HTML, text.toLowerCase().replace(/[^a-z0-9]/g, '')) ?? "";
  
    if (!this.listGenerateId.includes(sanitizedText) && !withoutPush) {
      this.listGenerateId.push(sanitizedText);
    }
  
    return sanitizedText;
  }
  
// Fonction pour défiler jusqu'à un ID spécifique avec un smooth scroll
  scrollToId(id: string): void {
  const element = document.getElementById(id);
  if (element) {
    const yOffset = -100; // décalage en pixels

    const y = element.getBoundingClientRect().top + window.pageYOffset + yOffset;
    window.scrollTo({ top: y, behavior: 'smooth' });
  }
}

}



<div class="cms-html-renderer-container">
    <ng-container *ngFor="let d of data; let i = index">

        <!-- Display the right component -->
        <TitleAtom *ngIf="d.type === 'heading4'"  margin="auto" type="h4" text="{{ d.text }}" align="left" color="{{ colorTitle !== '' ? colorTitle : 'dark'}}" size="medium" weight="semi-bold"></TitleAtom>
        <TitleAtom *ngIf="d.type === 'heading3'"  margin="auto" type="h3" text="{{ d.text }}" align="left" color="{{ colorTitle !== '' ? colorTitle : 'dark'}}" size="intermediate" weight="semi-bold"></TitleAtom>
        <TitleAtom *ngIf="d.type === 'heading2'" [attr.id]="d.id" margin="auto" type="h2" text="{{ d.text }}" align="left" color="{{ colorTitle !== '' ? colorTitle : 'dark'}}" size="large" weight="semi-bold"></TitleAtom>
        <ParagraphAtom *ngIf="d.type === 'paragraph' && !isTable(d.text) && !isHeadline(d.text)" size="intermediate" weight="regular" align="left" text="{{ cms.textStyle(d) }}"></ParagraphAtom>
        <Image *ngIf="d.type === 'image'" imageExternal="{{ d.url }}" alt="{{ d.alt }}" width="auto" mobileWidth="auto" borderRadius="radius"></Image>

        <!-- Table -->
        <div *ngIf="isTable(d.text)" class="table" [innerHTML]="getTable(d.text)"></div>

        <!-- Headline -->
        <div *ngIf="isHeadline(d.text)" class="headline">
            <h4>
                <img src="assets/images/icons/chat.svg" alt="chat" >
                {{ getHeadline(d.text).headline_title }}
            </h4>
            <ng-container *ngFor="let b of getHeadline(d.text).headline_body">
                <p [innerHTML]="cms.textStyle(b)"></p>
            </ng-container>
        </div>

        <!-- Normal list -->
        <ul *ngIf="d.type === 'list-item' && (i - 1 < 0 || data[i - 1].type !== 'list-item')">
            <li *ngFor="let item of getListItem(i, d)">
                <ng-container *ngIf="item.spans && item.spans.length > 0 && item.spans[0].type === 'hyperlink'">
                    <a href="{{ item.spans[0].data.url }}" target="_blank">{{ item.text }}</a>
                </ng-container>

                <ng-container *ngIf="item.spans && item.spans.length > 0 && item.spans[0].type === 'strong'">
                    <p [innerHTML]="cms.textStyle(item)"></p>
                </ng-container>

                <ng-container *ngIf="item.spans == undefined || item.spans.length == 0 ">
                    <ng-container *ngIf="listGenerateId.includes(generateId(item.text,true))">
                        <a href="javascript:void(0)" (click)="scrollToId(generateId(item.text,true))">{{ item.text }}</a>
                    </ng-container>
                    <ng-container *ngIf="!listGenerateId.includes(generateId(item.text,true))">
                        {{ item.text }}
                    </ng-container>
                </ng-container>
            </li>
        </ul>





        <!-- Order list -->
        <!--    <ol *ngIf="d.type === 'o-list-item' && data[i-1].type !== 'o-list-item'">-->
        <ol *ngIf="d.type === 'o-list-item' && (i-1 < 0 || data[i-1].type !== 'o-list-item')">
            <li *ngFor="let item of getListItem(i, d)">
                <ng-container *ngIf="listGenerateId.includes(generateId(item.text,true))">
                    <a href="javascript:void(0)" (click)="scrollToId(generateId(item.text,true))">{{ item.text }}</a>
                </ng-container>
                <ng-container *ngIf="!listGenerateId.includes(generateId(item.text,true))">
                    {{ item.text }}
                </ng-container>
            </li>
        </ol>

        <!-- Add space between component -->
        <div class="separator"></div>
    </ng-container>
</div>
